stages:
  - build
  - deploy

build_apk:
  stage: build
  before_script:
    - cd frontend
    - echo "sdk.dir = $HOME/android-sdk" >> ./android/local.properties
    - sudo npm install
    - cd android
    - cp $HOME/my-release-key.keystore ./app/my-release-key.keystore
  script:
    - ./gradlew assembleRelease
    after_script:
    - sudo rm -rf ./frontend/node_modules
  artifacts:
    paths:
      - frontend/android/app/build/outputs/apk/release/app-release.apk

deploy_apk:
  stage: deploy
  script:
    - sudo cp frontend/android/app/build/outputs/apk/release/app-release.apk /var/www/html/releases/cinect.apk
