# Generated by Django 2.2.1 on 2019-05-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwipedRight',
            fields=[
                ('swiperightid', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('imdbid', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
