# Generated by Django 2.2.1 on 2019-05-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinect_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('groupid', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=17)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupUsers',
            fields=[
                ('groupuserid', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('groupid', models.IntegerField(default=-1)),
                ('username', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'groupusers',
            },
        ),
    ]
