# Generated by Django 2.2.1 on 2019-05-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinect_api', '0002_auto_20190530_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupusers',
            name='groupid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinect_api.Groups'),
        ),
    ]
