# Generated by Django 2.2.1 on 2019-05-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinect_api', '0003_auto_20190530_1040'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='swipedright',
            table='swipedright',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
