# Generated by Django 2.2.1 on 2019-05-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinect_api', '0006_auto_20190530_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swipedright',
            old_name='imdbid',
            new_name='movieid',
        ),
    ]
