# Generated by Django 2.2.1 on 2019-05-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinect_api', '0007_auto_20190530_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='groupuserid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='swipedright',
            name='swiperightid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
