# Generated by Django 2.2.1 on 2019-06-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinect_api', '0010_groupuser_swipedright_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupuser',
            old_name='useremail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='swipedright',
            old_name='useremail',
            new_name='email',
        ),
    ]
