# Generated by Django 2.2.1 on 2019-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinect_api', '0011_auto_20190603_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebookid',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
