# Generated by Django 2.2.1 on 2019-06-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinect_api', '0012_user_facebookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebookid',
            field=models.CharField(default='null', max_length=255, unique=True),
        ),
    ]
