# Generated by Django 2.1.7 on 2019-06-03 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinect_api', '0013_auto_20190603_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWatched',
            fields=[
                ('userwatchedid', models.AutoField(primary_key=True, serialize=False)),
                ('movieid', models.CharField(max_length=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinect_api.User')),
            ],
            options={
                'db_table': 'userwatched',
            },
        ),
    ]
