# Generated by Django 2.1.7 on 2019-06-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinect_api', '0015_auto_20190604_1344'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwatched',
            unique_together={('email', 'movieid')},
        ),
    ]
