# Generated by Django 2.2.1 on 2019-06-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinect_api', '0016_auto_20190605_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='null', max_length=92),
        ),
    ]
