# Generated by Django 2.2.1 on 2019-06-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinect_api', '0019_auto_20190607_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likesAction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='likesAnimation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='likesComedy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='likesFamily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='likesHorror',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='likesRomance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='likesScifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='likesThriller',
            field=models.BooleanField(default=False),
        ),
    ]
