# Generated by Django 2.2.1 on 2019-06-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinect_api', '0020_auto_20190611_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('ratingid', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=25)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinect_api.User')),
                ('movieid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinect_api.Movie')),
            ],
            options={
                'db_table': 'userRatings',
            },
        ),
    ]
