# Generated by Django 2.2.1 on 2019-06-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinect_api', '0021_userrating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('email', 'movieid')},
        ),
    ]
